// <auto-generated />
using System;
using AssetTrakr.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTrakr.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240421224836_MoveArchiveSystemSettingsToUser")]
    partial class MoveArchiveSystemSettingsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AssetTrakr.Models.ActionLog", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionId");

                    b.ToTable("ActionLogEntries");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnderWarranty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderReference")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.HasIndex("ContractId");

                    b.HasIndex("HardwareId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OperatingSystemId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetAttachment", b =>
                {
                    b.Property<int?>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("AssetAttachments");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetHardDrive", b =>
                {
                    b.Property<int>("HardDriveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetHardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeInGB")
                        .HasColumnType("INTEGER");

                    b.HasKey("HardDriveId");

                    b.HasIndex("AssetHardwareId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("AssetHardDrives");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetHardware", b =>
                {
                    b.Property<int>("AssetHardwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BiosSerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .HasColumnType("TEXT");

                    b.Property<int>("RamSizeInGB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamSticks")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetHardwareId");

                    b.ToTable("AssetHardware");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetNetworkAdapter", b =>
                {
                    b.Property<int>("NetworkAdapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetHardwareId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NetworkAdapterId");

                    b.HasIndex("AssetHardwareId");

                    b.ToTable("AssetNetworkAdapters");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetOperatingSystem", b =>
                {
                    b.Property<int>("OperatingSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("OperatingSystemId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("AssetOperatingSystems");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetPeriod", b =>
                {
                    b.Property<int?>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "PeriodId");

                    b.HasIndex("PeriodId");

                    b.ToTable("AssetPeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUrl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AssetTrakr.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgreementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContractId");

                    b.HasIndex("OrderRef")
                        .IsUnique();

                    b.HasIndex("UserAgreementId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("AssetTrakr.Models.ContractAttachment", b =>
                {
                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("ContractAttachments");
                });

            modelBuilder.Entity("AssetTrakr.Models.ContractPeriod", b =>
                {
                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractId", "PeriodId");

                    b.HasIndex("PeriodId");

                    b.ToTable("ContractPeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscriptionContract")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("AssetTrakr.Models.LicenseAttachment", b =>
                {
                    b.Property<int?>("LicenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LicenseId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("LicenseAttachments");
                });

            modelBuilder.Entity("AssetTrakr.Models.LicensePeriod", b =>
                {
                    b.Property<int?>("LicenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LicenseId", "PeriodId");

                    b.HasIndex("PeriodId");

                    b.ToTable("LicensePeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("AssetTrakr.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("AssetTrakr.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlatformId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("AssetTrakr.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCriteria")
                        .HasColumnType("INTEGER")
                        .HasComment("Whether or not the report has criteria that can be used during run time");

                    b.Property<bool>("IsUserVisible")
                        .HasColumnType("INTEGER")
                        .HasComment("Whether or not it will be visible in the Report Runner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("The type of report, i.e Asset, License etc.  Uses ParentType enum in c#.");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("ShortCode used at run time for getting reports since ReportId is never guranteed to be the same");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Description = "All assets without warranty assigned, does not include expired warranty.",
                            HasCriteria = false,
                            IsUserVisible = false,
                            Name = "Assets without Warranty",
                            ParentType = "Asset",
                            ShortCode = "awow"
                        },
                        new
                        {
                            ReportId = 2,
                            Description = "Shows all assets in the system of the chosen criteria type.",
                            HasCriteria = true,
                            IsUserVisible = true,
                            Name = "Assets of Type",
                            ParentType = "Asset",
                            ShortCode = "aot"
                        },
                        new
                        {
                            ReportId = 3,
                            Description = "Shows assets in the system with storage lower than the chosen threshold criteria.",
                            HasCriteria = true,
                            IsUserVisible = true,
                            Name = "Assets With Low Storage",
                            ParentType = "Asset",
                            ShortCode = "awls"
                        },
                        new
                        {
                            ReportId = 4,
                            Description = "Shows all assets in the system with warranty whether active or expired.",
                            HasCriteria = false,
                            IsUserVisible = true,
                            Name = "Assets with Warranty",
                            ParentType = "Asset",
                            ShortCode = "aww"
                        },
                        new
                        {
                            ReportId = 5,
                            Description = "Shows all assets in the system with all available fields.",
                            HasCriteria = false,
                            IsUserVisible = false,
                            Name = "All Assets with All Fields",
                            ParentType = "Asset",
                            ShortCode = "aawaf"
                        },
                        new
                        {
                            ReportId = 6,
                            Description = "Shows all licenses in the system with all available fields.",
                            HasCriteria = false,
                            IsUserVisible = false,
                            Name = "All Licenses with All Fields",
                            ParentType = "License",
                            ShortCode = "alwaf"
                        },
                        new
                        {
                            ReportId = 7,
                            Description = "Shows Cost of all Entities in the System",
                            HasCriteria = false,
                            IsUserVisible = true,
                            Name = "Cost Analysis",
                            ParentType = "Other",
                            ShortCode = "costAnal"
                        });
                });

            modelBuilder.Entity("AssetTrakr.Models.System.SystemInfo", b =>
                {
                    b.Property<int>("SysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatabaseCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SysId");

                    b.ToTable("SystemInfo");
                });

            modelBuilder.Entity("AssetTrakr.Models.System.SystemSetting", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultSettingValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingParentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Name = "AlertThreshold",
                            Category = 1,
                            DefaultEnabled = true,
                            DefaultSettingValue = "30",
                            Description = "How many days before something expires to notify the user. (0 if disabled)",
                            Enabled = true,
                            SettingParentType = "Alerts",
                            SettingValue = "30"
                        },
                        new
                        {
                            Name = "AutomaticBackups",
                            Category = 1,
                            DefaultEnabled = true,
                            DefaultSettingValue = "3",
                            Description = "Backup the database on application start.  Value dictacts amount of backups to keep.",
                            Enabled = true,
                            SettingParentType = "Database",
                            SettingValue = "3"
                        },
                        new
                        {
                            Name = "NoAssetsAdded",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Assets"
                        },
                        new
                        {
                            Name = "AssetsWithoutWarranty",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Assets"
                        },
                        new
                        {
                            Name = "AssetsWithExpiredWarranty",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Assets"
                        },
                        new
                        {
                            Name = "AssetsWithWarrantyExpiringSoon",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Assets"
                        },
                        new
                        {
                            Name = "AssetsWithoutAttachments",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Assets"
                        },
                        new
                        {
                            Name = "NoLicensesAdded",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Licenses"
                        },
                        new
                        {
                            Name = "LicensesWithExpiredSubscriptions",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Licenses"
                        },
                        new
                        {
                            Name = "LicensesWithSubscriptionsExpiringSoon",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Licenses"
                        },
                        new
                        {
                            Name = "LicensesWithoutAttachments",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Licenses"
                        },
                        new
                        {
                            Name = "NoContractsAdded",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Contracts"
                        },
                        new
                        {
                            Name = "ContractsExpiringSoon",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Contracts"
                        },
                        new
                        {
                            Name = "ContractsWithoutAttachments",
                            Category = 0,
                            DefaultEnabled = true,
                            Description = "Alert",
                            Enabled = true,
                            SettingParentType = "Contracts"
                        });
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.Asset", b =>
                {
                    b.HasOne("AssetTrakr.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("AssetTrakr.Models.Assets.AssetHardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("AssetTrakr.Models.Assets.AssetOperatingSystem", "OperatingSystem")
                        .WithOne("Asset")
                        .HasForeignKey("AssetTrakr.Models.Assets.Asset", "OperatingSystemId");

                    b.HasOne("AssetTrakr.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.Navigation("Contract");

                    b.Navigation("Hardware");

                    b.Navigation("Manufacturer");

                    b.Navigation("OperatingSystem");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetAttachment", b =>
                {
                    b.HasOne("AssetTrakr.Models.Assets.Asset", "Asset")
                        .WithMany("AssetAttachments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Attachment", "Attachment")
                        .WithMany("AssetAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetHardDrive", b =>
                {
                    b.HasOne("AssetTrakr.Models.Assets.AssetHardware", "AssetHardware")
                        .WithMany("HardDrives")
                        .HasForeignKey("AssetHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("AssetHardware");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetNetworkAdapter", b =>
                {
                    b.HasOne("AssetTrakr.Models.Assets.AssetHardware", "AssetHardware")
                        .WithMany("NetworkAdapters")
                        .HasForeignKey("AssetHardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetHardware");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetOperatingSystem", b =>
                {
                    b.HasOne("AssetTrakr.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetPeriod", b =>
                {
                    b.HasOne("AssetTrakr.Models.Assets.Asset", "Asset")
                        .WithMany("AssetPeriods")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Period", "Period")
                        .WithMany("AssetPeriods")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("AssetTrakr.Models.ContractAttachment", b =>
                {
                    b.HasOne("AssetTrakr.Models.Attachment", "Attachment")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Contract", "Contract")
                        .WithMany("ContractAttachments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AssetTrakr.Models.ContractPeriod", b =>
                {
                    b.HasOne("AssetTrakr.Models.Contract", "Contract")
                        .WithMany("ContractPeriods")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Period", "Period")
                        .WithMany("ContractPeriods")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("AssetTrakr.Models.License", b =>
                {
                    b.HasOne("AssetTrakr.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("AssetTrakr.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Manufacturer");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("AssetTrakr.Models.LicenseAttachment", b =>
                {
                    b.HasOne("AssetTrakr.Models.Attachment", "Attachment")
                        .WithMany("LicenseAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.License", "License")
                        .WithMany("LicenseAttachments")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("License");
                });

            modelBuilder.Entity("AssetTrakr.Models.LicensePeriod", b =>
                {
                    b.HasOne("AssetTrakr.Models.License", "License")
                        .WithMany("LicensePeriods")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetTrakr.Models.Period", "Period")
                        .WithMany("LicensePeriods")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("AssetTrakr.Models.Platform", b =>
                {
                    b.HasOne("AssetTrakr.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.Asset", b =>
                {
                    b.Navigation("AssetAttachments");

                    b.Navigation("AssetPeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetHardware", b =>
                {
                    b.Navigation("HardDrives");

                    b.Navigation("NetworkAdapters");
                });

            modelBuilder.Entity("AssetTrakr.Models.Assets.AssetOperatingSystem", b =>
                {
                    b.Navigation("Asset")
                        .IsRequired();
                });

            modelBuilder.Entity("AssetTrakr.Models.Attachment", b =>
                {
                    b.Navigation("AssetAttachments");

                    b.Navigation("ContractAttachments");

                    b.Navigation("LicenseAttachments");
                });

            modelBuilder.Entity("AssetTrakr.Models.Contract", b =>
                {
                    b.Navigation("ContractAttachments");

                    b.Navigation("ContractPeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.License", b =>
                {
                    b.Navigation("LicenseAttachments");

                    b.Navigation("LicensePeriods");
                });

            modelBuilder.Entity("AssetTrakr.Models.Period", b =>
                {
                    b.Navigation("AssetPeriods");

                    b.Navigation("ContractPeriods");

                    b.Navigation("LicensePeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
